def menuUser():
    print("/" * 30)
    print("CIFRADO DE MENSAJES - MOD29 \n")
    print("ELIJE UNA OPCIÓN DEL MENU: \n")
    print("1. Cifrar")
    print("1. Descifrar")
    print("3. Matriz aleatoria cuadrada")
    print("4. Verificar inversa")
    print("5. Buscar inversa")
    print("6. Salir")
    print("/" * 30)
